### ISSUE TITLE
Write Tutorial for Creating/Managing Resources

### ISSUE THREAD

**Issue by remixlearning** [craftsmancoding/repoman#13]
Is it possible to use repoman to store and update the resources?

IF so how would that be done?

**Comment by pk-informatics** [comment]
Hello,

How did you get it working?
I cant get it working to create multiple resources => they overwrite each other so i only get one resource
I have tried it with id set, emtpy id and without id and even the php and the json way?

**Comment by fireproofsocks** [comment]
Here's a tutorial: https://github.com/craftsmancoding/repoman/wiki/Tutorial--Resources

**Comment by pk-informatics** [comment]
Hello,

Thank you for the tutorial :)
I have a little improvement for the tutorial:
Highlight the Part with build_attributes =>
"To correctly seed Resources you also have to add     "build_attributes": {
      "modResource": {
        "preserve_keys": true,
        "update_object": true,
        "unique_key": "alias"
      }
    } in your composer.json file
"

**Comment by fireproofsocks** [comment]
Good idea.  Done.
