### ISSUE TITLE
bug with multiple tvs

### ISSUE THREAD

**Issue by pk-informatics** [craftsmancoding/repoman#26]
Hello,

I have defined multiple tvs in seperate php files - but only the first tv is in the correct category (package namespace) all other tvs are uncategorized, the linking between all tvs and the template works without any problems

Latest repoman from master
Modx 2.3.2 advanced

**Comment by fireproofsocks** [comment]
I can't reproduce this.  I did however add a dedicated tutorial for this: https://github.com/craftsmancoding/repoman/wiki/Tutorial--Templates-and-TVs
