### ISSUE TITLE
Tutorial or Simple Wiki page for managing System Settings 

### ISSUE THREAD

**Issue by mark-ellul** [craftsmancoding/repoman#28]
Hi,

I am not sure if the seed_data approach would be correct, but I think it would be very helpful if there was an example for using the seed_data approach for adding and updating System settings.

Or is there another way we can add system settings via code/repoman?

Thanks in advance

**Comment by fireproofsocks** [comment]
I've added this page: https://github.com/craftsmancoding/repoman/wiki/Tutorial--System-Settings

Hopefully that contains relevant information for the topic.  Please make suggestions where appropriate.
